AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: hellword-api

Globals:
  Function:
    Timeout: 160

Resources:

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.default
      CodeUri: functions/greeting/dist
      Layers:
        - !Ref GlobalDependenciesLayer
        - !Ref GlobalApiResponsesLayer
      Runtime: nodejs12.x
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  GlobalDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GlobalDependenciesLayer
      ContentUri: layers/global-dependencies
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs12.x
  GlobalApiResponsesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GlobalApiResponsesLayer
      ContentUri: layers/api-responses/dist
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs12.x
